title: இ தமிழ்
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - Readme.md
  - /docs/gst-basics.md
theme: jekyll-theme-cayman
description: eTamil Programming Language
