   [package]
   name = "etamil"
   version = "0.1.0"
   edition = "2021"

   [dependencies]
   inkwell = { version = "0.4", features = ["llvm14-0"] }

   [[bin]]
   name = "etamil"
   path = "src/bin/main.rs"
